### ISSUE TITLE
Can you update the instructions and create a longer video?

### ISSUE THREAD

**Issue by 3thmanE-Al-Hayek** [Leoid/AWSBurpCollaborator#1]
Following the instructions in your README, I did not get this working successfully. 

Initially, I had to install pip3 and the modules that were missing (paramiko, boto3). I now see the following error: 
`Traceback (most recent call last):
  File "deploy.py", line 12, in <module>
    ec2 = boto3.resource('ec2')
  File "/home/ubuntu/.local/lib/python3.5/site-packages/boto3/__init__.py", line 100, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/boto3/session.py", line 389, in resource
    aws_session_token=aws_session_token, config=config)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/botocore/session.py", line 835, in create_client
    client_config=config, api_version=api_version)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/botocore/client.py", line 85, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/botocore/client.py", line 287, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/botocore/args.py", line 73, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/botocore/args.py", line 153, in compute_client_args
    s3_config=s3_config,
  File "/home/ubuntu/.local/lib/python3.5/site-packages/botocore/args.py", line 218, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/botocore/args.py", line 301, in _resolve_endpoint
    service_name, region_name, endpoint_url, is_secure)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/botocore/client.py", line 361, in resolve
    service_name, region_name)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.`

Any guidance, please?

**Comment by iNoSec2** [comment]
https://teamrot.fi/self-hosted-burp-collaborator-with-custom-domain/

**Comment by Leoid** [comment]
Thanks @iNoSec2 <3
